### ISSUE TITLE
Backbone template load error when testing

### ISSUE THREAD

**Issue by drumanagh** [drumanagh/twinejs-app#8]
Clicking on a permanent passage link while on test mode results in the following error:

```
Uncaught node.js Error 

Error: Could not find template: '#templates .storyListView'
    at e (app://host/twinejs/dist/rsrc/js/twine.js:2:20126)
    at c.extend.loadTemplate (app://host/twinejs/dist/rsrc/js/twine.js:2:25907)
    at c.extend.load (app://host/twinejs/dist/rsrc/js/twine.js:2:25732)
    at Function.c.extend.get (app://host/twinejs/dist/rsrc/js/twine.js:2:25471)
    at Object.f.Renderer.render (app://host/twinejs/dist/rsrc/js/twine.js:2:26234)
    at f.CompositeView.f.CollectionView.extend.renderModel (app://host/twinejs/dist/rsrc/js/twine.js:3:2156)
    at f.CompositeView.f.CollectionView.extend.render (app://host/twinejs/dist/rsrc/js/twine.js:3:1674)
    at c.extend.show (app://host/twinejs/dist/rsrc/js/twine.js:2:23181)
    at Backbone.Router.extend.routes.stories (app://host/twinejs/dist/rsrc/js/twine.js:9:14853)
    at c.extend.execute (app://host/twinejs/dist/rsrc/js/twine.js:2:8918)[/quote]
```

**Comment by drumanagh** [comment]
Should be fixed in v1.3.0.
